# cassandra/docker-compose.yml
networks:
  cassandra-net:
    driver: bridge
  shared-net:
    external: true

services:
  cassandra-1:
    image: "cassandra:4.1"
    container_name: "cassandra-1"
    hostname: "cassandra-1"
    ports:
      - 9042:9042
    networks:
      - cassandra-net
      - shared-net
    environment:
      - CASSANDRA_CLUSTER_NAME=nosql-benchmark-cluster
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    volumes:
      - cassandra-node-1:/var/lib/cassandra:rw
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 1m
      start_period: 2m
      timeout: 30s
      retries: 5

  cassandra-2:
    image: "cassandra:4.1"
    container_name: "cassandra-2"
    hostname: "cassandra-2"
    networks:
      - cassandra-net
      - shared-net
    environment:
      - CASSANDRA_CLUSTER_NAME=nosql-benchmark-cluster
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    depends_on:
      cassandra-1:
        condition: service_healthy
    volumes:
      - cassandra-node-2:/var/lib/cassandra:rw
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 1m
      start_period: 2m
      timeout: 30s
      retries: 5

  cassandra-3:
    image: "cassandra:4.1"
    container_name: "cassandra-3"
    hostname: "cassandra-3"
    networks:
      - cassandra-net
      - shared-net
    environment:
      - CASSANDRA_CLUSTER_NAME=nosql-benchmark-cluster
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    depends_on:
      cassandra-2:
        condition: service_healthy
    volumes:
      - cassandra-node-3:/var/lib/cassandra:rw
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 1m
      start_period: 2m
      timeout: 30s
      retries: 5

volumes:
  cassandra-node-1:
  cassandra-node-2:
  cassandra-node-3: