# mongo/docker-compose.yml
services:
  mongo-cfg1:
    image: mongo:7.0
    container_name: mongo-cfg1
    command: ["mongod", "--configsvr", "--replSet", "cfgRS", "--port", "27019", "--bind_ip_all"]
    networks:
      - mongo-net
      - shared-net
    volumes:
      - mongo-cfg1-data:/data/configdb
    restart: always

  mongo-cfg2:
    image: mongo:7.0
    container_name: mongo-cfg2
    command: ["mongod", "--configsvr", "--replSet", "cfgRS", "--port", "27019", "--bind_ip_all"]
    networks:
      - mongo-net
      - shared-net
    volumes:
      - mongo-cfg2-data:/data/configdb
    restart: always

  mongo-cfg3:
    image: mongo:7.0
    container_name: mongo-cfg3
    command: ["mongod", "--configsvr", "--replSet", "cfgRS", "--port", "27019", "--bind_ip_all"]
    networks:
      - mongo-net
      - shared-net
    volumes:
      - mongo-cfg3-data:/data/configdb
    restart: always

  mongo-shard1a:
    image: mongo:7.0
    container_name: mongo-shard1a
    command: ["mongod", "--shardsvr", "--replSet", "shard1RS", "--port", "27018", "--bind_ip_all"]
    networks:
      - mongo-net
      - shared-net
    volumes:
      - mongo-shard1a-data:/data/db
    restart: always

  mongo-shard1b:
    image: mongo:7.0
    container_name: mongo-shard1b
    command: ["mongod", "--shardsvr", "--replSet", "shard1RS", "--port", "27018", "--bind_ip_all"]
    networks:
      - mongo-net
      - shared-net
    volumes:
      - mongo-shard1b-data:/data/db
    restart: always

  mongo-shard1c:
    image: mongo:7.0
    container_name: mongo-shard1c
    command: ["mongod", "--shardsvr", "--replSet", "shard1RS", "--port", "27018", "--bind_ip_all"]
    networks:
      - mongo-net
      - shared-net
    volumes:
      - mongo-shard1c-data:/data/db
    restart: always

  mongo-mongos:
    image: mongo:7.0
    container_name: mongo-mongos
    command: >
      mongos --configdb cfgRS/mongo-cfg1:27019,mongo-cfg2:27019,mongo-cfg3:27019
      --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - mongo-net
      - shared-net
    depends_on:
      - mongo-cfg1
      - mongo-cfg2
      - mongo-cfg3
      - mongo-shard1a
      - mongo-shard1b
      - mongo-shard1c
    restart: always

volumes:
  mongo-cfg1-data:
  mongo-cfg2-data:
  mongo-cfg3-data:
  mongo-shard1a-data:
  mongo-shard1b-data:
  mongo-shard1c-data:

networks:
  mongo-net:
    driver: bridge
  shared-net:
    external: true
